### ISSUE TITLE
Bulk downloading of tiles from openstreetmap.org is strongly discouraged

### ISSUE THREAD

**Issue by JesseCrocker** [tyorke/EHOSMTilesDownloader#1]
Bulk downloading of tiles from openstreetmap.org is strongly discouraged, and downloading tiles at zooms >= 17 is prohibited. This project encourages bulk downloads, and the default zoom range is 1-18, which is a very bad choice.

If you need bulk downloads, you should either setup your own tile server, or pay a commercial provider.

I would suggest you remove this library from github and cocoapods, change the default server, or limit the zoom levels that can be downloaded. If you go for the option of changing the default server, you should put in a check and if the server is openstreetmap.org do not allow downloads of >= zoom 17.

For reference see http://wiki.openstreetmap.org/wiki/Tile_usage_policy#Bulk_Downloading

**Comment by tyorke** [comment]
I thought that users of the library should always check usage policy, so this project shouldn't be build and release into public app, but used only as tool when need to copy and store certain tiles region for their offline need.
But yes, probably it's better I'll remove it from github and cocoapods completely, as it might be misused. Thank you!
